version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15-stretch-browsers
    steps:
      - checkout
      - run: cd src && g++ -std=c++11  main.cpp -o main && ./main
      - run: mkdir build && cd build && cmake ..
test:
  override:
    - cd bin; ./gtest_myint
