version: 2
environment:
    PATH: "/home/ubuntu/cmake-3.6.2-Linux-x86_64/bin:$PATH"

jobs:
  build:
    docker:
      - image: circleci/python:2.7.15-stretch-browsers
    steps:
      - run: apt update && apt install -y binutils make cmake
      - checkout
      - run: cd src && g++ -std=c++11  main.cpp -o main && ./main
      - run: mkdir build && cd build && cmake ..
test:
  override:
    - cd bin; ./gtest_myint
