version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: cd src && clang++ -std=c++11  main.cpp -o main
      - run: main
test:
  override:
    - cd bin; ./gtest_myint
