# ccicpp/.circleci/config.yml
---
version: 2

jobs:
  build:
    docker:
      - image: robotlocomotion/circleci:xenial

    # working_directory: ~/asdf/ccicpp

    steps:
      - run:
          name: setup
          command: |
            echo "In setup..."
            apt update && apt install -y g++ cmake

      - checkout

      - run:
          name: build and test
          command: |
            echo "In build and test..."
            mkdir build && cd build && cmake .. && make -j8 && make test
