version: 2
jobs:
  build:
    docker:
      - image: circleci/c++
    steps:
      - checkout
      - run: cd src && g++ -std=c++11  main.cpp -o main && ./main
      - run: ./src/main
test:
  override:
    - cd bin; ./gtest_myint
